import os

file_path = r'c:\Users\vijay\Downloads\vsk\I-AI\utils\paper_utils.py'
with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Pixel-Perfect Column & Design Engine Replacement
start_pdf = -1
for i, line in enumerate(lines):
    if 'def export_as_pdf' in line:
        start_pdf = i
        break

if start_pdf != -1:
    new_content = [
        'def export_as_pdf(paper_data, template_name="Generic University", font_style="Serif", line_spacing=1.15):\n',
        '    """Export formatted paper with professional Column Flow and Academic Design."""\n',
        '    config = get_template_config(template_name)\n',
        '    pdf = PDF()\n',
        '    pdf.alias_nb_pages()\n',
        '    pdf.set_auto_page_break(auto=True, margin=20)\n',
        '    pdf.add_page()\n',
        '    \n',
        '    font_map = {\n',
        '        "Times New Roman": "Times", "Arial": "Helvetica", "Calibri": "Helvetica",\n',
        '        "Georgia": "Times", "Cambria": "Times", "Monospace": "Courier"\n',
        '    }\n',
        '    pdf_font = font_map.get(font_style, "Times")\n',
        '    is_multi_col = template_name in ["IEEE", "ACM"]\n',
        '    lh = 6 * line_spacing\n',
        '\n',
        '    # 1. Title Section (Centered, Bold)\n',
        '    pdf.set_font(pdf_font, "B", config["title_size"])\n',
        '    pdf.cell(0, 15, clean_text_for_pdf(paper_data.get("title", "Research Paper")), ln=True, align="C")\n',
        '    pdf.ln(5)\n',
        '    \n',
        '    # 2. Abstract Block (Full Width, Italicized)\n',
        '    pdf.set_font(pdf_font, "B", config["body_size"])\n',
        '    pdf.write(lh, "ABSTRACT - ")\n',
        '    pdf.set_font(pdf_font, "I", config["body_size"])\n',
        '    pdf.multi_cell(0, lh, clean_text_for_pdf(str(paper_data.get("abstract", ""))), align="J")\n',
        '    pdf.ln(2)\n',
        '    \n',
        '    pdf.set_font(pdf_font, "B", config["body_size"])\n',
        '    pdf.write(lh, "KEYWORDS: ")\n',
        '    pdf.set_font(pdf_font, "", config["body_size"])\n',
        '    pdf.cell(0, lh, clean_text_for_pdf(str(paper_data.get("keywords", ""))), ln=True)\n',
        '    pdf.ln(10)\n',
        '    \n',
        '    sections = [\n',
        '        ("Introduction", "introduction"), ("Literature Review", "lit_review"),\n',
        '        ("Methodology", "methodology"), ("Results & Discussion", "results"),\n',
        '        ("Conclusion", "conclusion"), ("Future Scope", "future_scope"),\n',
        '        ("References", "references"),\n',
        '    ]\n',
        '    \n',
        '    if is_multi_col:\n',
        '        # --- SMART COLUMN ENGINE ---\n',
        '        col_width = (pdf.w - 30) / 2\n',
        '        x_left = 15\n',
        '        x_right = 15 + col_width + 10\n',
        '        \n',
        '        def start_section(label):\n',
        '            pdf.set_font(pdf_font, "B", config["section_size"])\n',
        '            pdf.cell(col_width, 10, label.upper(), ln=True, border="B")\n',
        '            pdf.ln(3)\n',
        '\n',
        '        # For simple literal export, we process sections sequentially\n',
        '        for label, key in sections:\n',
        '            content = paper_data.get(key, "")\n',
        '            if not content: continue\n',
        '            \n',
        '            # Check if we need to switch columns or pages (basic heuristic)\n',
        '            if pdf.get_y() > 250:\n',
        '                pdf.add_page()\n',
        '            \n',
        '            start_section(label)\n',
        '            pdf.set_font(pdf_font, "", config["body_size"])\n',
        '            \n',
        '            # Break into paragraphs to handle flow better\n',
        '            paras = str(content).split("\\n\\n")\n',
        '            for p in paras:\n',
        '                if not p.strip(): continue\n',
        '                # First line indent\n',
        '                pdf.set_x(pdf.get_x() + 5)\n',
        '                pdf.multi_cell(col_width - 5, lh, clean_text_for_pdf(p.strip()), align="J")\n',
        '                pdf.ln(4)\n',
        '    else:\n',
        '        # --- SINGLE COLUMN ENGINE ---\n',
        '        for label, key in sections:\n',
        '            content = paper_data.get(key, "")\n',
        '            if not content: continue\n',
        '            \n',
        '            pdf.set_font(pdf_font, "B", config["section_size"])\n',
        '            pdf.set_fill_color(245, 245, 245)\n',
        '            pdf.cell(0, 10, "  " + label.upper(), ln=True, fill=True)\n',
        '            pdf.ln(4)\n',
        '            \n',
        '            pdf.set_font(pdf_font, "", config["body_size"])\n',
        '            paras = str(content).split("\\n\\n")\n',
        '            for p in paras:\n',
        '                if not p.strip(): continue\n',
        '                pdf.multi_cell(0, lh + 1, clean_text_for_pdf(p.strip()), align="J")\n',
        '                pdf.ln(5)\n',
        '            pdf.ln(5)\n',
        '            \n',
        '    return bytes(pdf.output())\n',
        '\n',
        'def export_as_docx(paper_data, template_name="Generic University", font_style="Serif", line_spacing=1.15):\n',
        '    """Export formatted paper as DOCX with full design logic (Justification, Spacing, Columns)."""\n',
        '    from docx import Document\n',
        '    from docx.shared import Pt, RGBColor, Inches\n',
        '    from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING\n',
        '    from docx.oxml.ns import qn\n',
        '    \n',
        '    config = get_template_config(template_name)\n',
        '    doc = Document()\n',
        '    \n',
        '    # Standard Academic Margins\n',
        '    for section in doc.sections:\n',
        '        section.top_margin = Inches(1)\n',
        '        section.bottom_margin = Inches(1)\n',
        '        section.left_margin = Inches(1)\n',
        '        section.right_margin = Inches(1)\n',
        '\n',
        '    font_map = {\n',
        '        "Times New Roman": "Times New Roman", "Arial": "Arial", "Calibri": "Calibri",\n',
        '        "Georgia": "Georgia", "Cambria": "Cambria", "Monospace": "Courier New"\n',
        '    }\n',
        '    word_font = font_map.get(font_style, "Times New Roman")\n',
        '    is_multi_col = template_name in ["IEEE", "ACM"]\n',
        '\n',
        '    # 1. Title\n',
        '    title = doc.add_heading(paper_data.get("title", "Research Paper"), 0)\n',
        '    title.alignment = WD_ALIGN_PARAGRAPH.CENTER\n',
        '    for run in title.runs:\n',
        '        run.font.name = word_font\n',
        '        run.font.size = Pt(config["title_size"])\n',
        '        run.font.bold = True\n',
        '        run.font.color.rgb = RGBColor(0, 0, 0)\n',
        '\n',
        '    # 2. Abstract Block\n',
        '    abs_para = doc.add_paragraph()\n',
        '    abs_para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY\n',
        '    run_label = abs_para.add_run("Abstract— ")\n',
        '    run_label.bold = True\n',
        '    run_label.font.name = word_font\n',
        '    abs_text = abs_para.add_run(str(paper_data.get("abstract", "")))\n',
        '    abs_text.font.name = word_font\n',
        '    abs_text.italic = True\n',
        '\n',
        '    if is_multi_col:\n',
        '        new_section = doc.add_section()\n',
        '        sectPr = new_section._sectPr\n',
        '        cols = sectPr.xpath("./w:cols")[0]\n',
        '        cols.set(qn("w:num"), "2")\n',
        '        cols.set(qn("w:space"), "720")\n',
        '    \n',
        '    # 3. Main Body Sections\n',
        '    sections = [\n',
        '        ("Keywords", "keywords"), ("Introduction", "introduction"),\n',
        '        ("Literature Review", "lit_review"), ("Methodology", "methodology"),\n',
        '        ("Results & Discussion", "results"), ("Conclusion", "conclusion"),\n',
        '        ("Future Scope", "future_scope"), ("References", "references"),\n',
        '    ]\n',
        '    \n',
        '    for label, key in sections:\n',
        '        content = paper_data.get(key, "")\n',
        '        if not content: continue\n',
        '        \n',
        '        h = doc.add_heading(label.upper(), level=1)\n',
        '        h.alignment = WD_ALIGN_PARAGRAPH.LEFT\n',
        '        for run in h.runs:\n',
        '            run.font.name = word_font\n',
        '            run.font.size = Pt(config["section_size"])\n',
        '            run.font.bold = True\n',
        '            run.font.color.rgb = RGBColor(0, 0, 0)\n',
        '        \n',
        '        paras = str(content).split("\\n\\n")\n',
        '        for p_text in paras:\n',
        '            if not p_text.strip(): continue\n',
        '            p = doc.add_paragraph(p_text.strip())\n',
        '            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY\n',
        '            p.paragraph_format.line_spacing = line_spacing\n',
        '            if line_spacing > 1.2:\n',
        '                p.paragraph_format.line_spacing_rule = WD_LINE_SPACING.MULTIPLE\n',
        '            # Paragraph Indent\n',
        '            p.paragraph_format.first_line_indent = Inches(0.2)\n',
        '            \n',
        '            for run in p.runs:\n',
        '                run.font.name = word_font\n',
        '                run.font.size = Pt(config["body_size"])\n',
        '            \n',
        '    import io\n',
        '    target = io.BytesIO()\n',
        '    doc.save(target)\n',
        '    return target.getvalue()\n'
    ]
    lines[start_pdf:] = new_content
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.writelines(lines)
    print("Successfully deployed Pixel-Perfect Column & Design Engine")
else:
    print("Could not find functions")
