import os

file_path = r'c:\Users\vijay\Downloads\vsk\I-AI\utils\paper_utils.py'
with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Re-implementing both export functions with full template awareness
start_pdf = -1
for i, line in enumerate(lines):
    if 'def export_as_pdf' in line:
        start_pdf = i
        break

if start_pdf != -1:
    new_content = [
        'def export_as_pdf(paper_data, template_name="Generic University", font_style="Serif"):\n',
        '    """Export formatted paper as PDF with full template awareness."""\n',
        '    config = get_template_config(template_name)\n',
        '    pdf = PDF()\n',
        '    pdf.alias_nb_pages()\n',
        '    pdf.set_auto_page_break(auto=True, margin=15)\n',
        '    pdf.add_page()\n',
        '    \n',
        '    # Font Mapping\n',
        '    font_map = {\n',
        '        "Times New Roman": "Times", "Arial": "Helvetica", "Calibri": "Helvetica",\n',
        '        "Georgia": "Times", "Cambria": "Times", "Monospace": "Courier"\n',
        '    }\n',
        '    pdf_font = font_map.get(font_style, "Times")\n',
        '    # Templates that use 2 columns\n',
        '    is_multi_col = template_name in ["IEEE", "ACM"]\n',
        '\n',
        '    # 1. Title (Full Width)\n',
        '    pdf.set_font(pdf_font, "B", config["title_size"])\n',
        '    pdf.cell(0, 20, clean_text_for_pdf(paper_data.get("title", "Research Paper")), ln=True, align="C")\n',
        '    pdf.ln(5)\n',
        '    \n',
        '    # 2. Abstract & Keywords (Full Width)\n',
        '    pdf.set_font(pdf_font, "B", config["body_size"])\n',
        '    pdf.write(7, "ABSTRACT: ")\n',
        '    pdf.set_font(pdf_font, "", config["body_size"])\n',
        '    pdf.multi_cell(0, 7, clean_text_for_pdf(str(paper_data.get("abstract", ""))), align="J")\n',
        '    pdf.ln(2)\n',
        '    \n',
        '    pdf.set_font(pdf_font, "B", config["body_size"])\n',
        '    pdf.write(7, "KEYWORDS: ")\n',
        '    pdf.set_font(pdf_font, "", config["body_size"])\n',
        '    pdf.cell(0, 7, clean_text_for_pdf(str(paper_data.get("keywords", ""))), ln=True)\n',
        '    pdf.ln(5)\n',
        '    \n',
        '    # 3. Main Body Sections\n',
        '    sections = [\n',
        '        ("Introduction", "introduction"), ("Literature Review", "lit_review"),\n',
        '        ("Methodology", "methodology"), ("Results & Discussion", "results"),\n',
        '        ("Conclusion", "conclusion"), ("Future Scope", "future_scope"),\n',
        '        ("References", "references"),\n',
        '    ]\n',
        '    \n',
        '    if is_multi_col:\n',
        '        col_width = (pdf.w - 30) / 2\n',
        '        for label, key in sections:\n',
        '            content = paper_data.get(key, "")\n',
        '            if not content: continue\n',
        '            pdf.set_font(pdf_font, "B", config["section_size"])\n',
        '            pdf.cell(col_width, 10, label.upper(), ln=True)\n',
        '            pdf.set_font(pdf_font, "", config["body_size"])\n',
        '            pdf.multi_cell(col_width, 6, clean_text_for_pdf(str(content)), align="J")\n',
        '            pdf.ln(5)\n',
        '    else:\n',
        '        for label, key in sections:\n',
        '            content = paper_data.get(key, "")\n',
        '            if not content: continue\n',
        '            pdf.set_font(pdf_font, "B", config["section_size"])\n',
        '            pdf.set_fill_color(240, 240, 240)\n',
        '            pdf.cell(0, 10, label.upper(), ln=True, fill=True)\n',
        '            pdf.ln(2)\n',
        '            pdf.set_font(pdf_font, "", config["body_size"])\n',
        '            pdf.multi_cell(0, 7, clean_text_for_pdf(str(content)), align="J")\n',
        '            pdf.ln(4)\n',
        '            \n',
        '    return bytes(pdf.output())\n',
        '\n',
        'def export_as_docx(paper_data, template_name="Generic University", font_style="Serif"):\n',
        '    """Export formatted paper as DOCX with full template awareness."""\n',
        '    from docx import Document\n',
        '    from docx.shared import Pt\n',
        '    from docx.enum.text import WD_ALIGN_PARAGRAPH\n',
        '    from docx.oxml.ns import qn\n',
        '    \n',
        '    config = get_template_config(template_name)\n',
        '    doc = Document()\n',
        '    \n',
        '    font_map = {\n',
        '        "Times New Roman": "Times New Roman", "Arial": "Arial", "Calibri": "Calibri",\n',
        '        "Georgia": "Georgia", "Cambria": "Cambria", "Monospace": "Courier New"\n',
        '    }\n',
        '    word_font = font_map.get(font_style, "Times New Roman")\n',
        '    is_multi_col = template_name in ["IEEE", "ACM"]\n',
        '\n',
        '    # 1. Title (Full Width)\n',
        '    title = doc.add_heading(paper_data.get("title", "Research Paper"), 0)\n',
        '    title.alignment = WD_ALIGN_PARAGRAPH.CENTER\n',
        '    for run in title.runs:\n',
        '        run.font.name = word_font\n',
        '        run.font.size = Pt(config["title_size"])\n',
        '        run._element.rPr.rFonts.set(qn("w:eastAsia"), word_font)\n',
        '\n',
        '    # 2. Abstract & Keywords (Full Width)\n',
        '    abs_para = doc.add_paragraph()\n',
        '    run_label = abs_para.add_run("ABSTRACT: ")\n',
        '    run_label.bold = True\n',
        '    run_label.font.name = word_font\n',
        '    abs_text = abs_para.add_run(str(paper_data.get("abstract", "")))\n',
        '    abs_text.font.name = word_font\n',
        '    abs_para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY\n',
        '\n',
        '    # 3. Handle Multi-Column Sections\n',
        '    if is_multi_col:\n',
        '        new_section = doc.add_section()\n',
        '        sectPr = new_section._sectPr\n',
        '        cols = sectPr.xpath("./w:cols")[0]\n',
        '        cols.set(qn("w:num"), "2")\n',
        '        cols.set(qn("w:space"), "720")\n',
        '    \n',
        '    # 4. Main Body\n',
        '    sections = [\n',
        '        ("Keywords", "keywords"), ("Introduction", "introduction"),\n',
        '        ("Literature Review", "lit_review"), ("Methodology", "methodology"),\n',
        '        ("Results & Discussion", "results"), ("Conclusion", "conclusion"),\n',
        '        ("Future Scope", "future_scope"), ("References", "references"),\n',
        '    ]\n',
        '    \n',
        '    for label, key in sections:\n',
        '        content = paper_data.get(key, "")\n',
        '        if not content: continue\n',
        '        h = doc.add_heading(label.upper(), level=1)\n',
        '        for run in h.runs:\n',
        '            run.font.name = word_font\n',
        '            run.font.size = Pt(config["section_size"])\n',
        '            run.font.color.rgb = None\n',
        '            run._element.rPr.rFonts.set(qn("w:eastAsia"), word_font)\n',
        '        p = doc.add_paragraph(str(content))\n',
        '        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY\n',
        '        for run in p.runs:\n',
        '            run.font.name = word_font\n',
        '            run.font.size = Pt(config["body_size"])\n',
        '            run._element.rPr.rFonts.set(qn("w:eastAsia"), word_font)\n',
        '            \n',
        '    import io\n',
        '    target = io.BytesIO()\n',
        '    doc.save(target)\n',
        '    return target.getvalue()\n'
    ]
    lines[start_pdf:] = new_content
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.writelines(lines)
    print("Successfully updated all templates for export")
else:
    print("Could not find functions")
